const motivationalQuotes = [
  "Push yourself, because no one else is going to do it for you.",
  "Success doesn’t just find you. You have to go out and get it.",
  "Don’t watch the clock; do what it does. Keep going.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Small progress is still progress.",
  "Dream it. Believe it. Build it.",
  "The secret of getting ahead is getting started.",
  "Discipline is choosing between what you want now and what you want most.",
  "Be stronger than your excuses.",
  "Consistency is more important than perfection.",
  "Stay patient and trust your journey.",
  "Doubt kills more dreams than failure ever will.",
  "The only way to do great work is to love what you do.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Great things never come from comfort zones.",
  "Believe you can and you're halfway there.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Don’t be afraid to give up the good to go for the great.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Action is the foundational key to all success.",
  "Never give up. Great things take time.",
  "You miss 100% of the shots you don’t take.",
  "One day or day one. You decide.",
  "The best view comes after the hardest climb.",
  "You are capable of amazing things.",
  "A little progress each day adds up to big results.",
  "Don't limit your challenges. Challenge your limits.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Opportunities don't happen. You create them.",
  "Don’t wish it were easier; wish you were better.",
  "Nothing will work unless you do.",
  "Don’t stop until you’re proud.",
  "Do something today that your future self will thank you for.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "You get what you work for, not what you wish for.",
  "Stay focused and never give up.",
  "Your only limit is your mind.",
  "If it doesn’t challenge you, it doesn’t change you.",
  "Success is what happens after you have survived all your mistakes.",
  "Your passion is waiting for your courage to catch up.",
  "Stop being afraid of what could go wrong, and start being excited about what could go right.",
  "Failure is not the opposite of success; it’s part of success.",
  "Sometimes later becomes never. Do it now.",
  "Learn as if you will live forever, live like you will die tomorrow.",
  "Motivation gets you going, but discipline keeps you growing.",
  "If you want to fly, give up everything that weighs you down.",
  "Surround yourself with people who see your value and remind you of it.",
  "You don’t always get what you wish for, you get what you work for.",
  "When you feel like quitting, remember why you started.",
  "You have to fight through some bad days to earn the best days of your life.",
  "Hustle in silence and let your success make the noise.",
  "Strength doesn’t come from what you can do. It comes from overcoming the things you once thought you couldn’t.",
  "Winners are not afraid of losing. But losers are. Failure is part of the process of success.",
  "Work hard in silence, let success be your noise.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "It's not about having time. It's about making time.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "What you do today can improve all your tomorrows.",
  "Your time is limited, so don’t waste it living someone else’s life.",
  "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
  "Do the hard work, especially when you don’t feel like it.",
  "If you’re tired, do it tired.",
  "Start where you are. Use what you have. Do what you can.",
  "Don’t quit. Suffer now and live the rest of your life as a champion.",
  "A winner is a dreamer who never gives up.",
  "You are never too old to set another goal or to dream a new dream.",
  "Never stop learning, because life never stops teaching.",
  "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice.",
  "Don’t compare your beginning to someone else’s middle.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "Difficult roads often lead to beautiful destinations.",
  "You don't find willpower, you create it.",
  "Focus on being productive instead of busy.",
  "Start small. Think big. Don’t stop.",
  "If you're going through hell, keep going.",
  "Don’t count the days, make the days count.",
  "Success starts with self-discipline.",
  "Go the extra mile. It’s never crowded.",
  "Wake up with a purpose.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don’t wait for opportunity. Create it.",
  "Don’t let yesterday take up too much of today.",
  "It always seems impossible until it’s done.",
  "When nothing goes right, go left.",
  "If you can dream it, you can do it.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Success is not for the lazy.",
  "Work until your idols become your rivals.",
  "Don’t wish for it. Work for it.",
  "Be a warrior, not a worrier.",
  "Prove them wrong.",
  "Fall seven times, stand up eight.",
  "Don’t downgrade your dream just to fit your reality.",
  "Let your faith be bigger than your fear.",
  "No pressure, no diamonds.",
  "Do it with passion or not at all.",
  "Doubt is a killer. You just have to know who you are and what you stand for.",
  "A river cuts through rock not because of its power, but because of its persistence.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Don’t fear failure. Fear being in the exact same place next year as you are today.",
  "Push yourself, because no one else is going to do it for you.",
  "Success doesn’t just find you. You have to go out and get it.",
  "Don’t watch the clock; do what it does. Keep going.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Small progress is still progress.",
  "Dream it. Believe it. Build it.",
  "The secret of getting ahead is getting started.",
  "Discipline is choosing between what you want now and what you want most.",
  "Be stronger than your excuses.",
  "Consistency is more important than perfection.",
  "Doubt kills more dreams than failure ever will.",
  "Work hard in silence. Let your success be your noise.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Great things never come from comfort zones.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "The future depends on what you do today.",
  "The expert in anything was once a beginner.",
  "Start where you are. Use what you have. Do what you can.",
  "Success is what comes after you stop making excuses.",
  "You are capable of more than you know.",
  "If you want it, work for it.",
  "Don’t limit your challenges. Challenge your limits.",
  "Don’t be afraid to give up the good to go for the great.",
  "A little progress each day adds up to big results.",
  "You miss 100% of the shots you don’t take.",
  "Winners are not people who never fail, but people who never quit.",
  "If it doesn’t challenge you, it doesn’t change you.",
  "Your limitation—it’s only your imagination.",
  "The best way to get started is to quit talking and begin doing.",
  "It always seems impossible until it’s done.",
  "You don’t need to see the whole staircase, just take the first step.",
  "Believe you can and you're halfway there.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Stay focused and never give up.",
  "Learn as if you will live forever, live like you will die tomorrow.",
  "Success is not in what you have, but who you are.",
  "Make each day your masterpiece.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Don’t wait for opportunity. Create it.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Believe in yourself and all that you are.",
  "There is no substitute for hard work.",
  "You are never too old to set another goal or to dream a new dream.",
  "Success usually comes to those who are too busy to be looking for it.",
  "It’s never too late to be what you might have been.",
  "Strive for progress, not perfection.",
  "Act as if what you do makes a difference. It does.",
  "The way to get started is to quit talking and begin doing.",
  "Failure will never overtake me if my determination to succeed is strong enough.",
  "Don’t wish it were easier. Wish you were better.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Start where you are. Use what you have. Do what you can.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "Don’t count the days, make the days count.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "If you’re going through hell, keep going.",
  "Do something today that your future self will thank you for.",
  "Don’t let yesterday take up too much of today.",
  "Success isn’t always about greatness. It’s about consistency.",
  "Perseverance is not a long race; it’s many short races one after the other.",
  "You get what you focus on, so focus on what you want.",
  "The best view comes after the hardest climb.",
  "Never stop learning, because life never stops teaching.",
  "Chase your dreams but always know the road that’ll lead you home again.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "Opportunities don't happen. You create them.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Do not wait to strike till the iron is hot, but make it hot by striking.",
  "Setting goals is the first step in turning the invisible into the visible.",
  "You don’t find willpower, you create it.",
  "Dream big and dare to fail.",
  "Learn from the mistakes of others. You can’t live long enough to make them all yourself.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The man who moves a mountain begins by carrying away small stones.",
  "You don’t need perfect conditions to succeed. Just a burning desire to make it happen.",
  "Your only limit is your mind.",
  "There are no shortcuts to any place worth going.",
  "Be so good they can’t ignore you.",
  "The real opportunity for success lies within the person and not in the job.",
  "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
  "Live your beliefs and you can turn the world around.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Big journeys begin with small steps.",
  "One day or day one. You decide.",
  "If you can dream it, you can do it.",
  "Just believe in yourself. Even if you don’t, pretend that you do and eventually you will.",
  "Progress is progress, no matter how small.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "You have to expect things of yourself before you can do them.",
  "You’re braver than you believe, and stronger than you seem, and smarter than you think.",
  "Whatever you are, be a good one.",
  "Don't watch the clock; do what it does. Keep going.",
  "Failure is the condiment that gives success its flavor.",
  "Turn your wounds into wisdom.",
  "Limit your 'always' and your 'nevers'.",
  "You are more than capable. Believe it, live it.",
  "Be a voice, not an echo.",
  "Don’t quit. Suffer now and live the rest of your life as a champion.",
  "The best revenge is massive success.",
  "Fall seven times, stand up eight."
];
export default motivationalQuotes;